services:
  web:
    build: .
    ports:
      - 80:80
      - 443:443
      - 8807:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dpanel
networks:
  dpanel:
    name: dpanel-local
